"""
Django settings for S34 project.

Generated by 'django-admin startproject' using Django 4.2.7.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-#d67z+i_5ec6dg8+))q-qw(d9y02o7g1!es5l&iol@lc6=oc&i'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'django_filters',
    'api',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'S34.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'S34.wsgi.application'


# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

STATIC_URL = 'static/'

# REST_FRAMEWORK = {
#     'DEFAULT_FILTER_BACKENDS': ['django_filters.rest_framework.DjangoFilterBackend']
# }

'''
REST_FRAMEWORK:

এটি Django Rest Framework-এর জন্য কনফিগারেশন সেটিংস। এখানে বিভিন্ন সেটিংস যেমন: authentication, permission, এবং filtering নির্ধারণ করা যায়।
DEFAULT_FILTER_BACKENDS:

DRF-এ যখন API রিসোর্সগুলো ফিল্টার করা লাগে (যেমন: ডেটা ফিল্টার করা 'তারিখ', 'নাম', 'ক্যাটাগরি' অনুসারে), তখন ফিল্টার ব্যাকএন্ড বলে দেওয়া হয়।
এই ক্ষেত্রে DjangoFilterBackend ফিল্টারিংয়ের জন্য ব্যবহৃত হবে।
django_filters.rest_framework.DjangoFilterBackend:

এটি একটি ফিল্টারিং টুল যা DRF-এর সাথে ইন্টিগ্রেট করে ডেটা ফিল্টার করতে সাহায্য করে।
উদাহরণ: যদি আপনার Product API থাকে এবং আপনি প্রোডাক্টের দাম বা ক্যাটাগরির উপর ভিত্তি করে ডেটা ফিল্টার করতে চান, তাহলে এই ব্যাকএন্ড সেটআপ করতে হবে।
কেন এটি প্রয়োজন?
ফিল্টারিং API ডেটা ব্যবস্থাপনা সহজ করে।
ব্যবহারকারী বা ক্লায়েন্ট নির্দিষ্ট প্যারামিটার দিয়ে সহজেই তাদের প্রয়োজনীয় ডেটা পেতে পারে।
উদাহরণ: আপনার API এর URL এ /api/products/?price=500 এই রকমভাবে ফিল্টারিং করতে পারবেন।
'''

# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
