"""
Django settings for S31 project.

Generated by 'django-admin startproject' using Django 4.2.7.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-tm8hz#^2xb&m3_(y(a-aue46znz+pq(ad&bj=he+^ez3ccqo9*'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'api',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'S31.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'S31.wsgi.application'


# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

STATIC_URL = 'static/'

REST_FRAMEWORK ={
    'DEFAULT_THROTTLE_RATES':{
        'anon':'2/days',
        'user':'5/hour',
        'jack':'3/minute',
    }

}
'''
এই কোডটি Django Rest Framework-এর থ্রোটলিং সেটিংস কনফিগার করার জন্য ব্যবহৃত হচ্ছে। এখানে 'DEFAULT_THROTTLE_RATES' নামে একটি ডিকশনারি তৈরি করা হয়েছে যা বিভিন্ন ধরনের ইউজারদের জন্য থ্রোটলিং রেট নির্ধারণ করে দেয়।

ব্যাখ্যা:

'anon': '2/days'
এটি নির্দেশ করছে যে এনোনিমাস (anonymous) বা লগইন না করা ব্যবহারকারীরা প্রতিদিন সর্বোচ্চ ২টি রিকোয়েস্ট করতে পারবে।

'user': '5/hou'
এটি নির্দেশ করছে যে লগইন করা ব্যবহারকারীরা প্রতি ঘণ্টায় সর্বোচ্চ ৫টি রিকোয়েস্ট করতে পারবে। (এখানে 'hou' একটি টাইপো, 'hour' হওয়া উচিত)

'jack': '3/minute'
এটি নির্দেশ করছে যে 'jack' নামে যে ব্যবহারকারী আছে, সে প্রতি মিনিটে সর্বোচ্চ ৩টি রিকোয়েস্ট করতে পারবে।
'''
# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
